CREATE TABLE user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(64) NOT NULL,
  salt VARCHAR(32),
  PRIMARY KEY (id)
)ENGINE = InnoDB DEFAULT CHARSET=utf8;

